### ISSUE TITLE
Change Font Family in Subtitles Plugin

### ISSUE THREAD

**Issue by Stephanie889** [professionalthemes/Subtitles#91]
Hi,

I would like to know how I can change the font family in the Subtitles Plugin. The font of the subtitles should look different than the font of the headline. How can I achieve this? Great Plugin by the way!

I'm looking forward to your reply.

Best regards,
Stephanie

**Comment by philiparthurmoore** [comment]
Hi Stephanie,

The plugin itself ships with no font. If you are seeing the same font in your subtitle that you see in your normal title then that is expected behavior. If you would like to use a different font for your subtitle, you will need to use some custom CSS to achieve that. Did you have a particular font in mind for your subtitle? Thank you.

Philip Arthur Moore
CEO @ Professional Themes (https://professionalthemes.nyc/)
philip@professionalthemes.nyc
Facebook (https://www.facebook.com/ProThemesNYC/) / Twitter (https://twitter.com/ProThemesNYC) / Press Build (https://pressbuild.blog/)
US: +1-832-632-7465 (tel:+1-832-632-7465)
VN: +84-0169-525-7591 (tel:+84-0169-525-7591)
